name: proto.chat
favicon: null
layout_spectrum: 0.36597
typography_spectrum: 0.88582
title: Early stage technology chatter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f485b'
    - '#6087cc'
    - '#e7f4fa'
    - '#cdcbd6'
    - '#b2adb2'
  brandStrength: 0.3749876720830798
  lightness: 0.33221752173267305
  saturation: 0.6574757965281606
  rhythmicContrast: 0.05478540319018066
purpose: []
